version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mi_base_de_datos
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: usuario_admin
      MONGO_INITDB_ROOT_PASSWORD: contraseña_secreta
      MONGO_INITDB_DATABASE: mi_database
    volumes:
      - ./data:/data/db
